export let week3 = [
    { num: "1", home: "Jets", away: "Patriots", picked: "none", },
    { num: "2", home: "Colts", away: "Bears", picked: "none", },
    { num: "3", home: "Vikings", away: "Texans", picked: "none", },
    { num: "4", home: "Saints", away: "Eagles", picked: "none", },
    { num: "5", home: "Steelers", away: "Chargers", picked: "none", },
    { num: "6", home: "Buccaneers", away: "Broncos", picked: "none", },
    { num: "7", home: "Titans", away: "Packers", picked: "none", },
    { num: "8", home: "Browns", away: "Giants", picked: "none", },
    { num: "9", home: "Raiders", away: "Panthers", picked: "none", },
    { num: "10", home: "Seahawks", away: "Dolphins", picked: "none", },
    { num: "11", home: "Cardinals", away: "Lions", picked: "none", },
    { num: "12", home: "Cowboys", away: "Ravens", picked: "none", },
    { num: "13", home: "Rams", away: "49ers", picked: "none", },
    { num: "14", home: "Falcons", away: "Chiefs", picked: "none", },
    { num: "15", home: "Bills", away: "Jaguars", picked: "none", },
    { num: "16", home: "Bengals", away: "Commanders", picked: "none", },
];
